name: Deploy the Product Page to GitHub Pages

env: # Change these to your preferences any image url can also be a base encoded image
  GITHUB_PAGES_BRANCH: gh-pages

  # options: "true" | "false"
  USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: "false"

  # Connected Repository
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  GITHUB_REPOSITORY_URL: ${{ github.event.repository.url }}
  GITHUB_API_BASE_URL: https://api.github.com/repos/${{ github.repository }}/contents
  GITHUB_DOCS_DIRECTORY_PATHS: '[{"name": "Documentatie", "location": "/docs"}]'

  # Links
  SLACK_URL: "https://join.slack.com/t/conductionworkspace/shared_invite/zt-1y5kerime-amWEvljvnLvo5S3YfU_jzg"
  READ_THE_DOCS_URL: "https://commongateway.readthedocs.io/en/latest/"

  # Navbar
  NAVBAR_LOGO_URL: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI1LjIuMywgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAxNzUuNCA0Mi4yIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCAxNzUuNCA0Mi4yOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxwYXRoIGQ9Ik03OC4zLDQwLjdoNy4yVjAuNGgtNy4yVjQwLjd6IE05NC44LDQwLjdoNy4yVjAuNGgtNy4yVjQwLjd6IE02NC41LDkuNEw1My40LDIwLjhsLTExLTExLjRsLTQuOCw0LjlsMTEuMSwxMS40TDM3LjYsMzcuMQoJbDQuOCw0LjlsMTEuMS0xMS40bDExLDExLjRsNC44LTQuOUw1OC4yLDI1LjdsMTEuMS0xMS40TDY0LjUsOS40eiBNMjcuMiw5LjRMMTYuMSwyMC44TDUuMSw5LjRsLTQuOCw0LjlsMTEuMSwxMS40TDAuMywzNy4xTDUuMSw0MgoJbDExLjEtMTEuNGwxMSwxMS40bDQuOC00LjlMMjAuOSwyNS43TDMyLDE0LjNMMjcuMiw5LjR6IE0xMjQuOCwxMC43Yy04LjIsMC0xNC4zLDUuMi0xNC4zLDE0LjF2MTUuOWg3LjJWMjVjMC00LjgsMy03LjMsNy4xLTcuMwoJczcuMSwyLjYsNy4xLDcuM3YxNS44aDcuMnYtMTZDMTM5LjEsMTUuOCwxMzMsMTAuNywxMjQuOCwxMC43eiBNMTYwLjQsMzQuOGMtNC41LDAtOC4yLTMuOS04LjItOC44YzAtNC44LDMuNy04LjgsOC4yLTguOAoJYzMuNCwwLDYuMywyLjIsNy41LDUuM2g3LjJjLTEuMy03LTcuMS0xMS44LTE0LjYtMTEuOGMtOC44LDAtMTUuMiw2LjUtMTUuMiwxNS40YzAsOC44LDYuNCwxNS4zLDE1LjIsMTUuMwoJYzcuNSwwLDEzLjMtNC44LDE0LjYtMTEuN2gtNy4yQzE2Ni42LDMyLjYsMTYzLjcsMzQuOCwxNjAuNCwzNC44eiIvPgo8L3N2Zz4K"

  # Footer
  FOOTER_LOGO_URL: "https://xxllnc.nl/wp-content/uploads/2021/04/xxllnc-kleur.svg"
  FOOTER_LOGO_HREF: "https://xxllnc.nl/"

  # Jumbotron
  JUMBOTRON_TITLE: "(Open) WOO Website Template"
  JUMBOTRON_SUBTITLE: "Product page"
  JUMBOTRON_DESCRIPTION: ${{ github.event.repository.description }}
  JUMBOTRON_SVG: "https://uploads.magnetme-images.com/bf3b2064d7a7c8a51b2c66608b62160f01ee478ab2df8a493635c92069405d35?auto=compress&auto=format&fit=crop&frame=0&h=1125&w=2000"


  # Other
  FAVICON_URL: "https://xxllnc.nl/wp-content/uploads/2021/07/cropped-fav-xxllnc-32x32.png"

  # NL Design Theme
  NL_DESIGN_THEME_CLASSNAME: "xxllnc-theme"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the Product Website Template Code
        uses: actions/checkout@v2
        with:
          repository: ConductionNL/product-website-template
          ref: development

      # With special thanks to https://github.com/SpicyPizza/create-envfile
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
          envkey_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ env.USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX }}
          envkey_GATSBY_GITHUB_API_BASE_URL: ${{ env.GITHUB_API_BASE_URL }}
          envkey_GATSBY_FAVICON_URL: ${{ env.FAVICON_URL }}
          envkey_GATSBY_NAVBAR_LOGO_URL: ${{ env.NAVBAR_LOGO_URL }}
          envkey_GATSBY_GITHUB_DOCS_DIRECTORY_PATHS: ${{ env.GITHUB_DOCS_DIRECTORY_PATHS }}
          envkey_GATSBY_SLACK_URL: ${{ env.SLACK_URL }}
          envkey_GATSBY_GITHUB_REPOSITORY_URL: ${{ env.GITHUB_REPOSITORY_URL }}
          envkey_GATSBY_JUMBOTRON_TITLE: ${{ env.JUMBOTRON_TITLE }}
          envkey_GATSBY_JUMBOTRON_SUBTITLE: ${{ env.JUMBOTRON_SUBTITLE }}
          envkey_GATSBY_JUMBOTRON_DESCRIPTION: ${{ env.JUMBOTRON_DESCRIPTION }}
          envkey_GATSBY_JUMBOTRON_SVG: ${{ env.JUMBOTRON_SVG }}
          envkey_GATSBY_FOOTER_LOGO_URL: ${{ env.FOOTER_LOGO_URL }}
          envkey_GATSBY_FOOTER_LOGO_HREF: ${{ env.FOOTER_LOGO_HREF }}
          envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ env.NL_DESIGN_THEME_CLASSNAME }}
          directory: pwa/static
          file_name: .env.production
          fail_on_empty: true
          sort_keys: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: cd pwa && npm install

      - name: Remove old Gatsby cache
        run: rm -rf pwa/.cache

      - name: Build application
        run: cd pwa && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: ${{ env.GITHUB_PAGES_BRANCH }}
          folder: pwa/public
